# paste config here

cache: apt
language: cpp

stages:
  - cache
  - test

jobs:
  include:
    - os: linux
      dist: xenial
      cache: ccache
      env:
        - CXX_COMPILER=/usr/bin/g++-7
        - C_COMPILER=/usr/bin/gcc-7
        - USE_MPI="false"
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - sourceline: 'ppa:mhier/libboost-latest'
          packages:
          - g++-7
          - pandoc
          - boost1.67
    - os: linux
      dist: xenial
      cache: ccache
      env:
        - CXX_COMPILER=/usr/bin/g++-8
        - C_COMPILER=/usr/bin/gcc-8
        - USE_MPI="false"
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - sourceline: 'ppa:mhier/libboost-latest'
          packages:
          - g++-8
          - pandoc
          - boost1.67
    - os: linux
      dist: bionic
      cache: ccache
      env:
        - CXX_COMPILER=/usr/bin/g++-9
        - C_COMPILER=/usr/bin/gcc-9
        - USE_MPI="false"
      addons:
        apt:
          sources:
          - sourceline: 'ppa:ubuntu-toolchain-r/test'
          packages:
          - g++-9
          - pandoc
          - libboost-all-dev
      deploy:
        provider: releases
        skip_cleanup: true
        api_key:
          secure: "Oag208LCu+WOhufBEYBngpIvBaVAO8cSQAbhOlfb17JFcSYP9aBryPkiEuSX7p6gHXmWGWy0C2Y5Pl/avaoFZpG9/9h0dhh4fuh9PgZ8LI26Fz7hPuQhFd3ewKjTcZCIhbHIBgTv/hPbFaltlEQfhR7hAjbFXZpCeXwBVWFt45X2R8xO/x7Wryw+eWIkXtj3L1Rsyjos3QHPSRQOcB9+mUfzn52g+MuVaNAm3RAnc3lgA27Vn3xyhdVk22Y2yV0hld/bUMmpm5T+ebcvJrkngRc56nFMUbK9dPsAkX8G7qvfoHmCVMTg7o+waymPjbLzR+4v1QTOegZO1YcDdz+SFyblPQah9bBOwpEw7RWgoTTz+T+/AT8hJpkuNSGyyEB4BlK3QOEz1eQBW/1FGK/TKRGnr6DHauKQu2ObQbaOXerFNis2Uv5uZWF92kbyw05yfSAAoMKUdr56bz6fMEFWYTDrYroN6imembxxzquCXuABhyTQZBjzEGMatUfe64wH/AH2Ong82iMPT6+ldu4IHN/p/ECwMcvfHrwD7t2TonQNC8zNNSH5mWtwIHLM/k7q/FlVZ8y5It89f+snPuZre+LE55LAFvfDomuicqb2FWAtAitNBMPzAJ5QtY3GyUXgjN9ajJiYqWjTeOPUEABlMpHIJ3y4a2jeQxeNzfwCneY="
        file: "${TRAVIS_BUILD_DIR}/projects/cmake/rb"
        on:
          repo: revbayes/revbayes
          branch: travisreleases
        draft: true
    - os: linux
      dist: xenial
      cache: ccache
      env:
        - CXX_COMPILER=/usr/bin/g++-7
        - C_COMPILER=/usr/bin/gcc-7
        - USE_MPI="true"
        - MPI_IMPL=openmpi
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - sourceline: 'ppa:mhier/libboost-latest'
          packages:
          - g++-7
          - pandoc
          - boost1.67
          - libopenmpi-dev
    - os: linux
      dist: xenial
      compiler: clang++
      cache: ccache
      env:
        - CXX_COMPILER=/usr/local/clang-7.0.0/bin/clang++
        - C_COMPILER=/usr/local/clang-7.0.0/bin/clang
        - USE_MPI="false"
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          - sourceline: 'ppa:mhier/libboost-latest'
          packages:
          - g++-8
          - pandoc
          - boost1.67
    - os: osx
      osx_image: xcode9.4
      env: PYTHON=3.5.1
        USE_MPI="false"
      addons:
       homebrew:
         update: true
         packages:
           - ccache
      install:
       - export PATH="/usr/local/opt/ccache/libexec:$PATH"
      cache: ccache
    - os: osx
      osx_image: xcode10.2
      env: PYTHON=3.5.1
        USE_MPI="false"
      addons:
       homebrew:
         packages:
           - ccache
      install:
       - export PATH="/usr/local/opt/ccache/libexec:$PATH"
      cache: ccache

    # # stage for building the cache, without tests
    # - stage: cache
    #   os: osx
    #   osx_image: xcode10.2
    #   env: PYTHON=3.5.1
    #     USE_MPI="false"
    #   addons:
    #    homebrew:
    #      packages:
    #        - ccache
    #   install:
    #    - export PATH="/usr/local/opt/ccache/libexec:$PATH"
    #   cache: ccache 
    # - os: osx
    #   osx_image: xcode9.4
    #   env: PYTHON=3.5.1
    #     USE_MPI="false"
    #   addons:
    #    homebrew:
    #      update: true
    #      packages:
    #        - ccache
    #   install:
    #    - export PATH="/usr/local/opt/ccache/libexec:$PATH"
    #   cache: ccache

before_install:
  # We need to re-export CC and CXX here, because travis exports CXX=g++ or clang++ AFTER we set CXX.
  - if [ -n "${C_COMPILER}" ]; then sudo update-alternatives --install /usr/bin/gcc  gcc "${C_COMPILER}"  90; fi
  - if [ -n "${CXX_COMPILER}" ]; then sudo update-alternatives --install /usr/bin/g++  g++ "${CXX_COMPILER}"  90; fi

script: ./travis-build.sh

# notifications
notifications:
  slack: revbayes:bQO6VTun0Orhx2NiKktVPDsS

